### ISSUE TITLE
Incorrect Dockerfile url reference in ansible-collection-system/molecule/*/Dockerfile.j2

### ISSUE THREAD

**Issue by bsriramprasad** [ericsysmin/ansible-collection-system#9]
Ref: https://ericsysmin.com/2020/04/30/ansible-collections-role-tests-with-molecule/

E.G Incorrect Dockerfile url reference in ansible-collection-system/molecule/chrony/Dockerfile.j2

{{ lookup('url', '**https://raw.githubusercontent.com/ericsysmin/docker-ansible-testing/master/**' ~ item.image ~ '/Dockerfile', split_lines=False) }}
 - highlighted URL seems a broken link

New reference : https://github.com/ericsysmin/docker-ansible-images/<distro-name> ?

**Comment by ericsysmin** [comment]
Thanks will get this resolved.
